-- Auto-generated from schema-map-postgres.yaml (map@sha1:FAEA49A5D5F8FAAD9F850D0F430ED451C5C1D707)
-- engine: postgres
-- table:  signatures

CREATE TABLE IF NOT EXISTS signatures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_table VARCHAR(64) NOT NULL,
  subject_pk    VARCHAR(64) NOT NULL,
  context       VARCHAR(64) NOT NULL,          -- e.g. 'audit_chain','event_outbox','asset'
  algo_id BIGINT NOT NULL,                     -- crypto_algorithms (class='sig')
  signing_key_id BIGINT NULL,                  -- identifies where the signature originates
  signature BYTEA NOT NULL,
  payload_hash BYTEA NOT NULL,                 -- e.g. SHA3-512 hash of the signed payload
  hash_algo_id BIGINT NOT NULL,                -- crypto_algorithms (class='hash')
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_signatures UNIQUE (subject_table, subject_pk, context, algo_id)
);
